### ISSUE TITLE
Topo route list has too many routes

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#112]
**What happened?**
The route list of topos does not match that of the topo image.

Compare the topos and the listed routes under each topo image of sector Ruinas en Gestalgar. For some topos those don't match.

Maybe related to https://github.com/theCrag/tca/issues/110
However, on this particular sector, Ruinas, I am not aware of any recent changes on the topos.

Example url(s) to reproduce the problem:

https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/2561079750/topo#t3374530185

Ideally also provide screenshots:

Website - route list matches drawn topo routes
![image](https://user-images.githubusercontent.com/30682796/116606657-52a57980-a931-11eb-886c-4630446a0301.png)

App - route list has additional routes
![image](https://user-images.githubusercontent.com/30682796/116606743-736dcf00-a931-11eb-973b-832bd11106ac.png)

App - no 27 is not in topo
![image](https://user-images.githubusercontent.com/30682796/116606786-84b6db80-a931-11eb-8c23-292bdf88c524.png)

Some more topos on this sector have the same issue

**What you expected:**

* [ ] Routes list per topo in app matches the routes linked to the topo image

FYI there are also crags where linked routes are not drawn, but the topo is still shown (in the website), e.g.
https://www.thecrag.com/es/escalar/spain/valencia/area/3067857549/topo#t3474850719

**Comment by andrasbari** [comment]
We receive all routes as the above example examines. We can hide the route from the list when the route descriptor (3rd argument) is null. @scd @rouletout what do you think? Hide the routes without path or stay visible?

The received data for this page: [https://user-images.githubusercontent.com/30682796/116606743-736dcf00-a931-11eb-973b-832bd11106ac.png](https://user-images.githubusercontent.com/30682796/116606743-736dcf00-a931-11eb-973b-832bd11106ac.png)

`
            [
               3374530191,
               1601330667,
               [
                  [
                     "Route",
                     3079161984,
                     null,
                     2561079750,
                     5
                  ],
                  [
                     "Route",
                     3079163736,
                     null,
                     2561079750,
                     6
                  ],
                  [
                     "Route",
                     3079166367,
                     null,
                     2561079750,
                     7
                  ],
                  [
                     "Route",
                     3079168224,
                     null,
                     null,
                     9999
                  ],
                  [
                     "Route",
                     3079169628,
                     null,
                     2561079750,
                     8
                  ],
                  [
                     "Route",
                     3079171029,
                     null,
                     2561079750,
                     9
                  ],
                  [
                     "Route",
                     3079172304,
                     "187.2 360.5,189.3 314.2,190.3 245.6,188.9 212.2,191.7 143 lower",
                     2561079750,
                     10
                  ],
                  [
                     "Route",
                     3079173666,
                     "203.3 366.1,203.3 325.6,203.4 301.1,210 269.1,201.6 188.7,203 154.8,205.3 130.3 lower",
                     2561079750,
                     11
                  ],
                  [
                     "Route",
                     3079175439,
                     "222.9 372.3,222.7 329.4,228.4 283.7,230.3 238.6,225.1 172.7,222.3 136 lower",
                     2561079750,
                     12
                  ],
                  [
                     "Route",
                     3079178721,
                     "261.5 376.4,261.5 326.2,260.8 275.3,252.4 223.5,244.4 163.7,245.3 115.3 lower",
                     2561079750,
                     14
                  ],
                  [
                     "Route",
                     3079211568,
                     "292.4 372.6,287.2 270.8,274.4 198.7,266.6 117.5 lower",
                     2561079750,
                     15
                  ],
                  [
                     "Route",
                     3079211655,
                     "314.9 370,313 333.9,312.1 283.3,302.2 227.7,292.4 183,283 149.2,280.6 117.6 lower",
                     2561079750,
                     16
                  ],
                  [
                     "Route",
                     3079211742,
                     "338.9 364.8,339.3 326.1,335.2 272.4,329.1 235.7,312.1 200,299.9 151,297.1 117.6 lower",
                     2561079750,
                     17
                  ],
                  [
                     "Route",
                     3079211829,
                     "354 356.3,355 324.3,352.6 280.9,351.2 241.8,344.1 177.4,325.8 114.3 lower",
                     2561079750,
                     18
                  ],
                  [
                     "Route",
                     3079211916,
                     "375.7 351.5,370.2 321.3,370.5 287,373.3 256.4,375.2 232,387.1 200.5,392.6 164.2 label,386.9 136,375.2 107.3 lower",
                     2561079750,
                     20
                  ],
                  [
                     "Route",
                     3079212003,
                     "375.7 351.5,370.2 321.3,370.5 287,373.3 256.4,375.2 232,365.8 193.4,358.7 151,375.2 107.3 lower",
                     2561079750,
                     19
                  ],
                  [
                     "Route",
                     3079212120,
                     "416.3 349.6,413.6 296.1,409.5 249.4,412.4 202.8,410.5 146.8,424.1 111.5 lower",
                     2561079750,
                     21
                  ]
               ],
               4608,
               3456,
               "8c6934d7489163fc649870ef174e94a513582cb9",
               null,
               2524410093
            ]

`

**Comment by rouletout** [comment]
I think they shouldn't show but I leave the technical solution to you @scd and @andrasbari

**Comment by rouletout** [comment]
Fixed, closing

**Comment by killakalle** [comment]
@rouletout
This is not fixed. The behavior looks still the same. Please, re-open this issue.
