### ISSUE TITLE
Topo image distorted

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#113]
**What happened?**
Go to sector Ruinas in Gestalgar, browse through the topos

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/2561079750/topo#t3374530185

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/30682796/116608601-b16bf280-a933-11eb-834a-4f7780d0fca1.png)

![image](https://user-images.githubusercontent.com/30682796/116608584-a87b2100-a933-11eb-980b-9ea61b25f038.png)

Looks normal on website
![image](https://user-images.githubusercontent.com/30682796/116608684-c779b300-a933-11eb-9a00-3d68c42593f1.png)

**What you expected:**

* [ ] Topo image not distorted

**Comment by andrasbari** [comment]
this issue was fixed on the back-end by @scd

**Comment by rouletout** [comment]
Still an issue, see also https://github.com/theCrag/tca/issues/118

**Comment by rouletout** [comment]
Clsoing in favor of https://github.com/theCrag/tca/issues/118
