### ISSUE TITLE
Area description is shown on route level

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#124]
**What happened?**
When there is no route description, then the app shows the area description. I think this is unnecessary and repetitive. 

Example url(s) to reproduce the problem:

This is a route without description
https://www.thecrag.com/es/escalar/spain/valencia/route/3945995805

![image](https://user-images.githubusercontent.com/30682796/117371423-286f3100-aec8-11eb-8649-3c6374df2b24.png)

![image](https://user-images.githubusercontent.com/30682796/117371447-2efda880-aec8-11eb-922b-5a956f800a1e.png)

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117370891-54d67d80-aec7-11eb-8f57-00fbd2790504.png)

**What you expected:**

* [ ] Area description (summary, approach, etc.) is not shown on route level

**Comment by rouletout** [comment]
Fixed, closing

**Comment by killakalle** [comment]
@rouletout 
This is not fixed. The behavior is still to show the area description on route level. Please, re-open this issue.

**Comment by bkucsera** [comment]
Reason of the behaviour: we show every inherited data in the route info sheet.
We will exclude the description from the inherited data types, only warnings will remain there, for the routes. Please send a feedback, if some other data also need to be inherited beyond warnings.

**Comment by scd** [comment]
@bkucsera both Ethic and Access are inherited descriptions.
